# Generated by Django 3.2 on 2022-10-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20221018_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='storetype',
        ),
        migrations.RemoveField(
            model_name='store',
            name='storetype',
        ),
        migrations.AddField(
            model_name='store',
            name='store_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
    ]
